Fix JVP rule for convert_element_type to integer types.
Without this fix, the newly added test fails:

```
File "/Users/necula/Source/jax/jax/_src/lax/lax.py", line 2382, in _convert_element_type_jvp_rule
    return ad_util.Zero(tangent.aval.update(dtype=dtypes.float0, weak_type=False))
                         ^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'aval'
```

because `tangent` is a float constant.