Make the repr of GetVmapParams and SetVmapParams more compact.
This is causing test failures with new hypothesis versions.

```
FAILED tests/state_test.py::StateHypothesisTest::test_addupdate_vmap - hypothesis.errors.HypothesisWarning: Generating overly large repr. This is an expensive operation, and with a length of 34 kB is unlikely to be useful. Use -Wignore to ignore the warning, or -Werror to get a traceback.
```

PiperOrigin-RevId: 929972410