Improve error message when passing a tuple of non-concrete values as an axis argument.
Previously, we would see the less helpful error:

```
jax._src.errors.TracerIntegerConversionError: The __index__() method was called on the JAX Tracer object Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=5/0)>
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerIntegerConversionError
```

Whereas now we see:

```
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The axis argument must be known statically.
While tracing the function h at /Users/phawkins/p/jax/tests/lax_numpy_test.py:3663 for jit, this concrete value was not available in Python because it depends on the value of the argument 'y'.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```