Ensure tests that use hypothesis call htu.setup_hypothesis().
This should fix a CI error:
```
ERROR: test_all_gather_2d_mesh__thread_3 (__main__.AllGatherTest)
AllGatherTest.test_all_gather_2d_mesh__thread_3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/.cache/bazel/bazel/_bazel_root/78563004db3df495dc7c02b4a6eb08ea/execroot/__main__/bazel-out/k8-opt/bin/tests/pallas/tpu_all_gather_test_tpu.runfiles/__main__/tests/pallas/tpu_all_gather_test.py", line 110, in test_all_gather_2d_mesh
    hps.sampled_from(["x", "y"]))
       ^^^^^^^
  File "/__w/.cache/bazel/bazel/_bazel_root/78563004db3df495dc7c02b4a6eb08ea/execroot/__main__/bazel-out/k8-opt/bin/tests/pallas/tpu_all_gather_test_tpu.runfiles/pypi_hypothesis/site-packages/hypothesis/core.py", line 1968, in wrapped_test
    fail_health_check(
  File "/__w/.cache/bazel/bazel/_bazel_root/78563004db3df495dc7c02b4a6eb08ea/execroot/__main__/bazel-out/k8-opt/bin/tests/pallas/tpu_all_gather_test_tpu.runfiles/pypi_hypothesis/site-packages/hypothesis/internal/healthcheck.py", line 21, in fail_health_check
    raise FailedHealthCheck(message)
hypothesis.errors.FailedHealthCheck: The method AllGatherTest.test_all_gather_2d_mesh was called from multiple different executors. This may lead to flaky tests and nonreproducible errors when replaying from database.

Unlike most health checks, HealthCheck.differing_executors warns about a correctness issue with your test. We therefore recommend fixing the underlying issue, rather than suppressing this health check. However, if you are confident this health check can be safely disabled, you can do so with @settings(suppress_health_check=[HealthCheck.differing_executors]). See https://hypothesis.readthedocs.io/en/latest/reference/api.html#hypothesis.HealthCheck for details.
```

PiperOrigin-RevId: 951448376