Raise a better error message if an empty mesh is passed to shard_map
Before:

```
ValueError: shard_map in_specs argument must refer to an axis marked as manual (frozenset()), but:

  in_specs refers to 'x'

Check the in_specs values passed to shard_map.
```

After:

```
ValueError: shard_map requires a non-empty mesh. Got Mesh()
```
PiperOrigin-RevId: 857255016