Restore `call_tf_concrete_function_list` to previous state
In the following case of nested call:

```
inputs = np.array(range(6), dtype=np.float32).reshape(3, 2)

@jax.jit
def forward(x):
	return x + 1

# JAX -> TF
tf_fn = jax2tf.convert(forward, native_serialization=True)
call_tf_fn = jax2tf.call_tf(tf_fn)
tf_fn_too = jax2tf.convert(call_tf_fn, native_serialization=True)

tf_fn_too(inputs)  # FAIL
```

Without the fix, it fails with the following error:

```
jax/experimental/jax2tf/jax2tf.py", line 499, in _restore_context
    _thread_local_state.call_tf_concrete_function_list.clear()
AttributeError: 'NoneType' object has no attribute 'clear'
```

because we call `_restore_context` twice when executing `jax2tf.convert`ed functions,
the first time we call `_restore_context`, `call_tf_concrete_function_list` is set to `None`
instead of restoring it to the previous state, so the second time we call `_restore_context`,
`call_tf_concrete_function_list.clear()` throws the above error since `call_tf_concrete_function_list` is `None`.

PiperOrigin-RevId: 536650377