[Mosaic GPU] Fix `MosaicGpuDialectTCGen05Test` tests.
Layout inference is failing with:
```
NotImplementedError: No layout inference rule defined for unrealized_conversion_cast
```

The TMEM scratch allocation logic is duplicating some logic that is currently part of the `tmem_alloc` instruction lowering. We don't need to issue a cast and instead return the result of the allocation.

PiperOrigin-RevId: 800446600