improve AOT input sharding/layout mismatch error message
Before:

```
ValueError: Compiled object called with input sharding(s) and layout(s) does not match the sharding(s) and layout(s) the computation was compiled with. Here are the 2 mismatches:
Got input sharding(s) that compiled object was called with: SingleDeviceSharding(device=CpuDevice(id=0), memory_kind=unpinned_host) and sharding(s) the computation was compiled with: NamedSharding(mesh=Mesh('x': 1, axis_types=(Auto,)), spec=PartitionSpec(), memory_kind=device) for arg x with shape: int32[8]
Got input layout(s) that compiled object was called with: Layout(major_to_minor=(0,), _tiling=(), _sub_byte_element_size_in_bits=0) and layout(s) the computation was compiled with: Layout(major_to_minor=(0,), _tiling=((128,),), _sub_byte_element_size_in_bits=0) for arg x with shape: int32[8]
```

After:

```
ValueError: Computation was compiled for input shardings and layouts that disagree with the shardings and layouts of arguments passed to it. Here are the 2 mismatches:
Argument x with shape int32[8]:
  Passed sharding: SingleDeviceSharding(device=CpuDevice(id=0), memory_kind=unpinned_host)
  Required sharding: NamedSharding(mesh=Mesh('x': 1, axis_types=(Auto,)), spec=PartitionSpec(), memory_kind=device)
Argument x with shape int32[8]:
  Passed layout: Layout(major_to_minor=(0,), _tiling=(), _sub_byte_element_size_in_bits=0)
  Required layout: Layout(major_to_minor=(0,), _tiling=((128,),), _sub_byte_element_size_in_bits=0)
```

Co-authored-by: Yash Katariya <yashkatariya@google.com>
PiperOrigin-RevId: 785284120