Mark a test as thread-unsafe.
We saw the following CI failure: https://github.com/jax-ml/jax/actions/runs/16741182406/job/47389854136

```
FAIL: test_pe_close_jaxpr_cache_leak (__main__.JitTest)
JitTest.test_pe_close_jaxpr_cache_leak
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/.cache/bazel/bazel/_bazel_root/a40625930fdef4f0a3483cd60aa1bb86/execroot/__main__/bazel-out/k8-opt/bin/tests/api_test_cpu.runfiles/__main__/tests/api_test.py", line 721, in test_pe_close_jaxpr_cache_leak
    self.assertEmpty(keys_2, 0)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
AssertionError: [(, ((), (), None, AbstractMesh((), axis_types=()), None, True, 'raise', None, False, False, 'strict', None, 0, True, False, True, False, False, False, 0, False, None, 3, False, True, False, 'ignore', 'ignore', 'ignore', False, None), (), {}), (, ((), (), None, AbstractMesh((), axis_types=()), None, True, 'raise', None, False, False, 'strict', None, 0, True, False, True, False, False, False, 0, False, None, 3, False, True, False, 'ignore', 'ignore', 'ignore', False, None), (), {})] has length of 2. : 0
```

The cache is shared between threads so this test is thread-unsafe.

PiperOrigin-RevId: 791777130