Remove `rep` completely from shard_map (rip rep from shmap -- RIP). The error message logic was the last standing thing using `rep`s. Now, the error message talks about varyingness rather than replication
Before:

```
ValueError: shard_map applied to the function 'f' was given out_specs which require replication which can't be statically inferred given the mesh:

The mesh given has shape (2, 2, 2) with corresponding axis names ('x', 'y', 'z').

out_specs is PartitionSpec('x',) which implies that the corresponding output value is replicated across mesh axes {y,z}, but could only infer replication over {}, which is missing the required axes y,z

Check if these output values are meant to be replicated over those mesh axes. If not, consider revising the corresponding out_specs entries. If so, consider disabling the check by passing the check_vma=False argument to `jax.shard_map`.
```

After:

```
ValueError: shard_map applied to the function 'f' was given out_specs which require replication which can't be statically inferred given the mesh:

The mesh given has shape (2, 2, 2) with corresponding axis names ('x', 'y', 'z').

out_specs is PartitionSpec('x',) which implies that the corresponding output value is only varying across mesh axes {x} and not {y,z}, but it was inferred to be possibly varying over {x,y,z}

Check if these output values are meant to be replicated over those mesh axes. If not, consider revising the corresponding out_specs entries. If so, consider disabling the check by passing the check_vma=False argument to `jax.shard_map`.
```

PiperOrigin-RevId: 751543307