[pallas] Move the import of tpu_custom_call from tests to a more central place.
Some tests import "jax.experimental.mosaic" or "jax._src.tpu_custom_call" only
to initialize the flags defined in tpu_custom_call.py. Otherwise, tests that end
up importing `tpu_custom_call` during lowering will result in an error:

```
AssertionError: Test changed global config values. Differing values are: {'jax_mosaic_allow_hlo': (<not present>, False), 'mosaic_use_python_pipeline': (<not present>, False)}
```

The real cause is that we conditionally import the mosaic and triton
lowering rules in pallas_call.py. Since we now support cross-platform
lowering, we should make those lowerings available unconditionally.
That would require adding the TPU and GPU ops dependencies to all
tests.

PiperOrigin-RevId: 650200888