Add spaces before dump instructions
Otherwise, the error message comes out weird and the instructions may be missed:

```
ValueError: Cannot lower jaxpr with verifier errors:
	'stablehlo.add' op requires compatible types for all operands and results
		at loc("jit(add)/jit(main)/add"("<module>"("/tmp/jax_exploration/main.py":7:6)))
	see current operation: %0 = "stablehlo.add"(%arg0, %arg1) : (tensor<i32>, tensor<f32>) -> tensor<i32>
		at loc("jit(add)/jit(main)/add"("<module>"("/tmp/jax_exploration/main.py":7:6)))Define JAX_DUMP_IR_TO to dump the module.
```

See also this error message in the docs: https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html#numpy-lax-xla-jax-api-layering (scroll horizontally to see the "Define JAX_DUMP_IR_TO ..." all the way to the right)

PiperOrigin-RevId: 639882828