[Pallas TPU] Expose accumulator references to be used with explicit MXU APIs.
If this CL breaks you due to the following error:

```
ValueError: Unsupported TPU device kind: cpu. If you are not running on a TPU device, you need to wrap your code in a `jax.sharding.use_abstract_mesh` context manager whose `AbstractMesh` argument specifies the exact TPU version you intend to target.
```

then you need to wrap your custom call compilation in a mesh as instructed in the error message.

Reverts effd7d771d33f5f7ab7bfdd49230ce3c82362515

PiperOrigin-RevId: 962144673