[Pallas:MGPU] Refine type of `plgpu.BlockSpec.transforms`.
`transforms` must be hashable. Using a `list` raises the following error:

```
TypeError: As of JAX v0.7, parameters to jaxpr equations must have __hash__ and __eq__ methods. In a call to primitive pallas_call, the value of parameter grid_mapping was not hashable: GridMapping(grid=(), block_mappings=(BlockMapping(block_shape=(Blocked(block_size=128), Blocked(block_size=128))), BlockMapping(block_shape=(Blocked(block_size=128), Blocked(block_size=128)))))
```
PiperOrigin-RevId: 828939404