Replace AvalDimSharding and MeshDimAssignment with the C++ object.
The sharding and mesh_mapping fields are lists (instead of the current tuple), but they are immutable (I mean that if you modify it, it won't be reflected on the C++ object. But because it's a list you can decide to modify it).

It's internal to JAX, so it limits the issues with the possible confusion of having lists and not tuples, but it massively simplify the C++ as the casts are trivial.

2 new `# type: ignore` are needed, because mypy does not understand that List[A] is a List[Union[A, B]]:

```
jax/interpreters/pxla.py:1132: error: Argument "mesh_mapping" to "ShardingSpec" has incompatible type "List[Replicated]"; expected "List[Union[ShardedAxis, Replicated]]"  [arg-type]
jax/interpreters/pxla.py:1132: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
```